-- NOTE: Run AFTER all migrations (01–07) complete successfully
-- PASSWORDS:
--   Admin   → username: Admin,   password: Admin123
--   Student → username: Student, password: Student123
-- =============================================================================

-- Clear existing data for clean re-seed
DELETE FROM NOTIFICATIONS;
DELETE FROM LEAVES;
DELETE FROM PROXY_DETECTION_LOGS;
DELETE FROM OTP_LOGS;
DELETE FROM ATTENDANCE;
DELETE FROM ADMIN;
DELETE FROM STUDENTS;

-- -------------------------------------------------------
-- ADMIN user: Admin / Admin123
-- bcrypt hash generated from Node.js: bcrypt.hashSync('Admin123', 12)
-- -------------------------------------------------------
INSERT INTO ADMIN (Username, Credentials, Full_Name, Email, Admin_Role, Department) VALUES
    ('Admin', '$2a$12$cYyRpA9McAjc5csO.gSNXe2F5eLIdv4NuQsJSTWe8ZlgJAj8hs01C',
     'System Administrator', 'admin@university.edu.pk', 'ADMIN', 'Computer Science');

-- -------------------------------------------------------
-- STUDENT user: Student / Student123
-- bcrypt hash generated from Node.js: bcrypt.hashSync('Student123', 12)
-- This is in the ADMIN table so they can authenticate via the same login endpoint
-- -------------------------------------------------------
INSERT INTO ADMIN (Username, Credentials, Full_Name, Email, Admin_Role, Department) VALUES
    ('Student', '$2a$12$/mHWmfJc/wAfZtnCdxgaxeiZkCXzy82L7q3ZZQwi6Dd8uMSHHi.s.',
     'Demo Student', 'student@university.edu.pk', 'STUDENT', 'Computer Science');

-- -------------------------------------------------------
-- STUDENTS table — 1 demo student matching the Student login
-- Student_ID will be auto-generated by SEQ_STUDENTS (starts at 1000)
-- -------------------------------------------------------
INSERT INTO STUDENTS (Name, Email, Phone, Guardian_Email, Guardian_Phone, Program, Semester, Section) VALUES
    ('Demo Student', 'student@university.edu.pk', '03001234567',
     'parent@gmail.com', '03009876543', 'BSCS', 1, 'A');

COMMIT;

-- -------------------------------------------------------
-- Quick sanity check — row counts
-- -------------------------------------------------------
SELECT 'ADMIN'                AS "Table", COUNT(*) AS "Rows" FROM ADMIN
UNION ALL
SELECT 'STUDENTS',                        COUNT(*) FROM STUDENTS;

PROMPT Seed data inserted successfully.
PROMPT   Admin login:   Username=Admin,   Password=Admin123
PROMPT   Student login: Username=Student, Password=Student123
