SET PAGESIZE 50000
SET LINESIZE 200
COLUMN USERNAME FORMAT A15
COLUMN FULL_NAME FORMAT A20
COLUMN EMAIL FORMAT A25
PROMPT --- ADMIN ---
SELECT Admin_ID, Username, Full_Name, Email, Admin_Role FROM ADMIN;
PROMPT --- STUDENTS ---
SELECT Student_ID, Name, Email FROM STUDENTS;
PROMPT --- ATTENDANCE ---
SELECT Attendance_ID, Student_ID, Log_Status, Log_Time FROM ATTENDANCE;
PROMPT --- LEAVES ---
SELECT Leave_ID, Student_ID, Log_Status, Reason FROM LEAVES;
EXIT;
