import { Request, Response } from 'express';
import { getStudentRepository } from '../repositories/StudentRepository';
import { success, serverError } from '../utils/response';
import { EnrollStudentRequest } from '../types';

export class StudentController {
  
  /** POST /api/students */
  static async createStudent(req: Request<{}, {}, EnrollStudentRequest>, res: Response) {
    try {
      // 1. Get repository
      const repo = getStudentRepository();

      // 2. Map input (adding defaults/mock data for optional fields)
      const studentData = {
        name: req.body.name,
        email: req.body.email,
        phone: req.body.phone || null,
        program: req.body.program || null,
        semester: req.body.semester || null,
        section: req.body.section || null,
        guardianEmail: req.body.guardianEmail || null,
        guardianPhone: req.body.guardianPhone || null,
        faceEncoding: null, // Would be generated by Python service in real flow
        imagePath: null
      };

      // 3. Save to repository
      const newStudent = await repo.create(studentData);

      // 4. Return response
      return success(res, newStudent, 'Student enrolled successfully', 201);
    } catch (error: any) {
      return serverError(res, error.message);
    }
  }
}
